var FieldVSpacing = 3 * Mappero.uiScale
var FieldHSpacing = 2 * Mappero.uiScale
var FileToolsWidth = 120 * Mappero.uiScale
var MenuButtonHeight = 72 * Mappero.uiScale
var MenuButtonFontPixelSize = 24 * Mappero.uiScale
var OsmButtonSize = 72 * Mappero.uiScale
var OsmScreenMargin = 8 * Mappero.uiScale
var PaneButtonHeight = 32 * Mappero.uiScale
var TagPaneHeight = 104 * Mappero.uiScale
var TaggableEmblemSize = 24 * Mappero.uiScale
var TaggableSourceWidth = TagPaneHeight - 4 * Mappero.uiScale
var TaggableSourceHeight = TaggableSourceWidth * Mappero.uiScale
var TaggableToolsSize = 32 * Mappero.uiScale
var ToolSpacing = 8 * Mappero.uiScale
var ToolbarMargins = 8 * Mappero.uiScale
var TextColor = "black"
var TextColorDisabled = "#888"
