var MenuButtonHeight = 72
var MenuButtonFontPixelSize = 24
var OsmButtonSize = 72
var OsmScreenMargin = 8
var TagPaneHeight = 120
var TaggableEmblemSize = 32
var TaggableSourceWidth = TagPaneHeight - 4
var TaggableSourceHeight = TaggableSourceWidth
var ToolSpacing = 8
