var FileToolsWidth = 120
var MenuButtonHeight = 72
var MenuButtonFontPixelSize = 24
var OsmButtonSize = 72
var OsmScreenMargin = 8
var PaneButtonHeight = 32
var TagPaneHeight = 104
var TaggableEmblemSize = 24
var TaggableSourceWidth = TagPaneHeight - 4
var TaggableSourceHeight = TaggableSourceWidth
var TaggableToolsSize = 32
var ToolSpacing = 8
